services:
  svelte-app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "80:5173"
    command: >
      sh -c "
      npm install &&
      npm run build &&
      npm install -g serve &&
      serve -s public -l 80"
