version: '3.8'
services:
  svelte-app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "
      npm install &&
      npm run build &&
      npm install -g serve &&
      serve -s public -l 5000"
