# Generated by Django 5.0.9 on 2024-09-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1
                    ),
                ),
                ("birth_date", models.DateField()),
                ("year_joined", models.IntegerField()),
                (
                    "unit_area",
                    models.CharField(
                        choices=[
                            ("AAS", "AAS"),
                            ("AFI", "AFI"),
                            ("AII", "AII"),
                            ("ASB", "ASB"),
                            ("DIR", "DIREÇÃO"),
                            ("UATP", "UATP"),
                            ("UPC", "UPC"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("E", "ESTAGIÁRIO"),
                            ("T", "TÉCNICO"),
                            ("C", "COORDENADOR"),
                            ("D", "DIREÇÃO"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
